services:
  backend:
    build:
      context: ./perfume-generator-backend
    ports:
      - "8080:8080"
    volumes:
      # Persister les uploads sur la machine (important)
      - ./perfume-generator-backend/uploads:/app/uploads

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./perfume-generator-frontend:/app
      # node_modules reste dans le container (Ã©vite soucis Windows)
      - /app/node_modules
    command: sh -c "npm ci && npm run start -- --host 0.0.0.0 --port 4200"
    ports:
      - "4200:4200"
    depends_on:
      - backend
